### PR TITLE
fix(pool): APR calculation

### LINKED ISSUE #118: APR value may not be latest
#### What happened:
The current calculation of APR may not be a latest value, because it is using the calling of rewardSpeed() method, which is not the most updated rewardSpeed all the time if users don't often call beforeHook() or any other functions that use beforeHook()

#### What you expected to happen:
We should calculate the latest value of rewardSpeed considering which epoch the liquidity mining program is in.
One example for fixing this is that we can try editing useUsdtRewardRate() in data/TotalSupply.ts like this one:
```
const USDT_POOL_INITIAL_REWARD_RATE = BigNumber.from(25 * 10 ** 6)
const EPOCH_LENGTH = BigNumber.from(6000 * 7)

export function useUsdtRewardRate() {
  let rewardRate: BigNumber
  const endColdStartBlockNum: BigNumber = useSingleCallResult(useUsdtLpContract(), 'endColdStartBlockNum')?.result?.[0]
  const currBlockNum: BigNumber = BigNumber.from(useBlockNumber())
  const stage: number = useSingleCallResult(useUsdtLpContract(), 'contract_stage')?.result?.[0]
  const totalStake: BigNumber = useSingleCallResult(useUsdtLpContract(), 'totalStake')?.result?.[0]
  if (!(endColdStartBlockNum && currBlockNum && stage && totalStake)) return undefined
  if (stage == 3) {
    rewardRate = BigNumber.from(0)
  } else {
    rewardRate = USDT_POOL_INITIAL_REWARD_RATE
    const currEpoch = currBlockNum.sub(endColdStartBlockNum).div(EPOCH_LENGTH)
    for (let i = 0; currEpoch.gt(i); i++) {
      rewardRate = rewardRate.mul(96).div(100)
    }
  }
  return [rewardRate, totalStake]
  // return rewardRate && totalStake ? [rewardRate, totalStake] : undefined
}

```

### PR DESCRIPTION
**Pull request by Abhishekkochar**
#### What this PR does / why we need it:
At the Current code, Apr will not get updated if there is no interaction with function updateIndex(). This leaves APR value to be not updated as time goes on.
#### Which issue(s) does this PR fixes?:

Fixes #118

### CODE REVIEW

**Comment by Abhishekkochar** [comment]
@gjj @cuongquangnam, Please review :)

**Comment by gjj** [comment]
I'll defer to @cuongquangnam's expert opinion. 😄

**Review by chee-chyuan — DISMISSED** [review]

File: src/pages/AddLiquidity/APRCalculation.tsx [hunk 1]
```diff
@@ -5,14 +5,29 @@ import BN from 'bignumber.js'
...
+    contractStage === undefined ||
+    currentBlockNum === undefined
+  )
+    return undefined
+  if (contractStage.toString() === '3') return (APR = 0)
+  let rewardRateBN = new BN(adminRate.toString())
   const totalStakeBN = new BN(totalStake.toString())
   const totalSupplyUniBN = new BN(totalSupplyUni.toString())
   const blocksPerWeek = 6000 * 7
+  const currEpoch = new BN(currentBlockNum.toString()).minus(endColBlock).div(blocksPerWeek)
```
Comment (cuongquangnam) [inline src/pages/AddLiquidity/APRCalculation.tsx:27]: currEpoch should be an integer, not a floating point number. 
Reason: if currEpoch = 2.5, then the loop below runs for 3 times, instead of 2 times as expected.
Therefore, we should use type @ethersproject/bignumber which is only used for integers

File: src/pages/AddLiquidity/APRCalculation.tsx [hunk 2]
```diff
@@ -5,14 +5,29 @@ import BN from 'bignumber.js'
...
+  for (let i = 0; currEpoch.gt(i); i++) {
+    rewardRateBN = rewardRateBN.times(96).div(100)
```
Comment (cuongquangnam) [inline src/pages/AddLiquidity/APRCalculation.tsx:29]: Besides, just to be more accurate, I'd suggest rewardRateBN to be of type @ethersproject/bignumber, as in the smart contracts, rewardSpeed is an integer actually.

Comment (Abhishekkochar) [reply src/pages/AddLiquidity/APRCalculation.tsx:29]: > Besides, just to be more accurate, I'd suggest rewardRateBN to be of type @ethersproject/bignumber, as in the smart contracts, rewardSpeed is an integer actually.

rewardSpeed is assigned as a unit not integer in smart contracts.

**Review by cuongquangnam — APPROVED** [review]
